{% set name = "qiskit-ibm-experiment" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-ibm-experiment-{{ version }}.tar.gz
  sha256: 08abd896a2c895f610b2793ee82e0499d1e56e6804b91c0cf9bc490125734813

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy >=1.13
    - pandas >=1.3.0
    - python >=3.8
    - python-dateutil >=2.8.0
    - qiskit-terra >=0.32,<1
    - requests >=2.19
    - requests_ntlm >=1.1.0
    - typing-extensions >=4.0.0
    - urllib3 >=1.21.1
    - pyyaml >=6.0.0

test:
  imports:
    - qiskit_ibm_experiment
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-ibm-experiment
  summary: Qiskit IBM Experiment service for accessing the quantum experiment interface at IBM
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
